### PR TITLE
Added TypeScript declaration file

### PR DESCRIPTION
**Pull request by cberg-zalando**
To make it easier for TypeScript users, I added a definition file, which should handle all exposed functionality of the library.

### CODE REVIEW

**Comment by ruiaraujo** [comment]
I would rather have the whole library converted to TS. :smile:
The library is informally typechecked using comment notations so it should be a matter of adding the tsconfig .

**Comment by cberg-zalando** [comment]
I only wanted to avoid the issue of adding the typing file to a local project of us, as it is always a hassle if having a multi folder project to setup the `tsconfig.json` file in a way that it finds the typings and still uses the ones in `node_modules/@types`. So for me this is the more sort term solution.

**Comment by cberg-zalando** [comment]
I actually created the definiton file using the Typescript compiler and just extended it with the comments as outlined in the README.md file. So I am not sure what you actually want to have regarding your `so it should be a matter of adding the tsconfig.`.

**Comment by ruiaraujo** [comment]
I would say that we add the ts compiler to the project and get the types as part of the build ensuring they stay up to date.

**Comment by cberg-zalando** [comment]
Would this be added to the `prepublish` phase as I currently don't see how this project is actually built.

**Comment by ruiaraujo** [comment]
@cberg-zalando yes. Currently this project doesn't require building.

**Comment by cberg-zalando** [comment]
I tried my luck with adding typescript as dev dependency, a corresponding `tsconfig.json` file to only generate the declaration files, but I am not really satisfied with the result, because

1. additional declaration files are generated for the files in the data directory (and two of them do not even work)
2. the generated declaration file is not really ideal

```ts
export function formattingForLocale(locale: string, currencyCode?: string | undefined): BanknoteFormatting;
export function currencyForCountry(twoCharacterCountryCode: string): string | undefined;
export function formatSubunitAmount(subunitAmount: number, formatting: BanknoteFormatting): string;
export type BanknoteFormatting = {
    showDecimalIfWhole: boolean;
    subunitsPerUnit: number;
    centsZeroFill: number;
    effectiveLocale: string;
    currencyCode: string;
    currencySymbol: string;
    currencyFormatter: Function;
    thousandSeparator: string;
    decimalSeparator: string;
};
```

in comparison to the refined one, I want to add in this PR.

**Comment by ruiaraujo** [comment]
@cberg-zalando can you push that to another branch? I dont think the generated types look  bad. :)

**Pull request closed without merging**
